services:
  - type: web
    name: mapa-acessibilidade-api
    env: node
    region: sao-paulo
    plan: free
    rootDir: Backend
    buildCommand: npm install && npm run db:migrate
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mapa-acessibilidade-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        sync: false

static_sites:
  - name: mapa-acessibilidade-frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    rootDir: frontend/UPX-IV
    envVars:
      - key: VITE_API_URL
        value: https://mapa-acessibilidade-api.onrender.com
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false

databases:
  - name: mapa-acessibilidade-db
    plan: free
    region: sao-paulo
    databaseName: mapa_acessibilidade
    user: mapa_acessibilidade_user

